logging:
   level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.jdbc.core: TRACE
server:
   port: 8080
   compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
      min-response-size: 1024
   servlet:
      session:
         cookie:
            http-only: true
spring:
   application:
      name: camunda
   jmx:
      default-domain: camunda-jmx
   main:
      allow-bean-definition-overriding: true
   jackson:
      serialization:
         indent-output: true
      mapper:
         sort-properties-alphabetically: false
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
   datasource:
      driver-class-name: org.h2.Driver
      url:  jdbc:h2:file:./camunda-h2-database
      username: sa
      password: root
      hikari:
         poolName: construction-pool
         auto-commit: true
         max-lifetime: 600000
         data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
   data:
      web:
         pageable:
            default-page-size: 10
            one-indexed-parameters: false
      jpa:
         repositories:
            bootstrap-mode: deferred
         open-in-view: false
         show-sql: true
         properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: true
            hibernate.generate_statistics: true
            hibernate.jdbc.batch_size: 20
         hibernate:
            ddl-auto: update
            naming:
               physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
               implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
   h2:
      console:
         enabled: true
         path: /h2-console
         settings:
            trace: false
            web-allow-others: false