logging:
   level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework.jdbc.core.JdbcTemplate: DEBUG
      org.springframework.jdbc.core: TRACE
server:
   port: 8080
   compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
      min-response-size: 1024
   servlet:
      session:
         cookie:
            http-only: true
spring:
   application:
      name: camunda
   main:
      allow-bean-definition-overriding: true
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
   datasource:
      driver-class-name: org.h2.Driver
      url:  jdbc:h2:file:./camunda-h2-database
      username: sa
      password: root
      hikari:
         poolName: construction-pool
         auto-commit: true
         max-lifetime: 600000
         data-source-properties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
   h2:
      console:
         enabled: true
         path: /h2-console
         settings:
            trace: false
            web-allow-others: false
camunda:
   bpm:
     admin-user:
       id: demo
       password: demo
       firstName: Demo
     filter:
       create: All taskss